### PR TITLE
Fix "use before define" issues so unspecified config keys are skipped; fix regexes; add missing globals; always ignore anteater_files

### PR DESCRIPTION
**Pull request by dskrvk**
Successfully tested on a local repo with minimal config files:

* ignore_list.yaml
```
project_exceptions:
  nullvalue

file_audits:
  file_contents:
    - "somevalue"
```
* file_list.yaml
```
file_audits:
  file_names:
    - \.asc
  file_contents:
    password:
        regex: password
        desc: "Hardcoding passwords is baad!"
```

### CODE REVIEW

**Review by lukehinds — APPROVED** [review]
Thanks @dskrvk !

**Comment by dskrvk** [comment]
Hey @lukehinds what are the next steps to getting this released?

**Comment by lukehinds** [comment]
> Hey @lukehinds what are the next steps to getting this released?

I will cut a release now. It's interesting that you're using anteater, please you're finding it useful. May I ask how you leverage the tool, perhaps on your CI (it's ok to not say if its internal work you need to keep private).

**Comment by lukehinds** [comment]
@dskrvk https://github.com/anteater/anteater/releases/tag/0.3.0

**Comment by dskrvk** [comment]
My goal is to use it for my team's Terraform project, initially in CI, and eventually in a pre-commit hook. A locally-patched version was already able to identify a few issues, so that's great. Thanks for creating the tool!

Sorry to be a bother, but v0.3.0 doesn't appear to be on pypi yet - is that a separate step?

**Comment by lukehinds** [comment]
@dskrvk ah, yep. will get that up this weekend!

**Comment by dskrvk** [comment]
Hi @lukehinds any chance you could get a new version released?

**Comment by lukehinds** [comment]
> Hi @lukehinds any chance you could get a new version released?

hey @dskrvk , sorry about that will do, I am hitting some issues with pypi not liking the readme formatting, will have a another try.

**Comment by dskrvk** [comment]
Let me know if I can help in any way.

**Comment by lukehinds** [comment]
@dskrvk , really sorry this has taken so long. You would not believe the issues I hit, I had 2fa on pypi and my freeOTP was on an old phone given to another family member.

all sorted now: https://pypi.org/project/anteater/

p.s. happy to add you as a collaborator on the project?

**Comment by dskrvk** [comment]
Sure, I’ll try to help with the project. Glad you sorted out the OTP issues.

**Pull request merged**
